### ISSUE TITLE
Kinetic: Hokuyo URG Node Param Names Incorrect

### ISSUE THREAD

**Issue by FernandezR** [utexas-bwi/segbot#107]
max_ang and min_ang params should be angle_max and angle_min for the urg node in kinetic. This could be causing some of our laser errors on the robots.

**Comment by jack-oquin** [comment]
Good. Would you commit those fixes to the "kinetic" branch?

**Comment by FernandezR** [comment]
Yes, I'll take care of it.

**Comment by FernandezR** [comment]
@jack-oquin Since you removed the angle filter hokuyo_filters_v2.yaml I believe we should add the angle_min and angle_max params from the hokuyo.launch file to the ethernet hokuyo launch file.

**Comment by FernandezR** [comment]
I also believe we should be using the default param "scan_filtered" for localization_scan_topic in segbot.launch.xml for amcl on the v4 instead of the current param "scan" that is passed by  segbot_v4.launch.

**Comment by jack-oquin** [comment]
You are probably right. Let's experiment with some of those parameters on the robots this afternoon. 

I think we could run the ``angle_range_filter`` now. It was commented out due to early problems building ``segbot_sensors_filters``. That seems to be working now, but the config file was never restored.

Thanks for investigating!

**Comment by jack-oquin** [comment]
I ran with ``angle_range_filter`` active, and the results were obviously better. Navigation was reasonably smooth.

**Comment by jack-oquin** [comment]
It seems to work fine with the angle min and max driver parameters: 4076825
